# Лабораторна робота 1. Аналіз даних
  [Посилання на GitHub](https://github.com/unIns1de/Homework-from-KSVD/blob/main/Bartosh_hw1_.ipynb)

1) Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

In [1]:
import numpy as np
vector = np.arange(1, 21)
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

2) Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [2]:
matrix = np.ones((4, 4), dtype=int)
matrix

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

3) Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [3]:
np.random.uniform(-1, 1, size=(5,5))

array([[-0.11049528, -0.80467054,  0.11008052,  0.31656224,  0.31186132],
       [ 0.46066987, -0.33225787, -0.24047012,  0.89939182,  0.36529404],
       [-0.55537836,  0.57133381, -0.72769976,  0.36217673,  0.14974005],
       [-0.63874351,  0.61173706,  0.17182893, -0.37046697, -0.99111133],
       [ 0.23588466, -0.61691186, -0.98479925, -0.64442157, -0.3799733 ]])

4) Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
np.random.uniform(0, 1, size=(3,3))

array([[0.51707863, 0.78949956, 0.95144217],
       [0.55429241, 0.0308517 , 0.97312832],
       [0.06546446, 0.07823602, 0.83351862]])

5) Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
matrix_1 = np.random.randint(1, 21, size=(1,6))
matrix_2 = np.random.randint(1, 21, size=(1,6))

print(f"matrix_1 = {matrix_1} \nb = {matrix_2}\n")
print(f"matrix_1 + matrix_2 = {matrix_1 + matrix_2}")
print(f"matrix_1 - matrix_2 = {matrix_1 - matrix_2}")
print(f"matrix_1 * matrix_2 = {matrix_1 * matrix_2}")

matrix_1 = [[15 20 14  9 18 16]] 
b = [[ 8 17 12  6  1  3]]

matrix_1 + matrix_2 = [[23 37 26 15 19 19]]
matrix_1 - matrix_2 = [[ 7  3  2  3 17 13]]
matrix_1 * matrix_2 = [[120 340 168  54  18  48]]


6) Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [18]:
matrix_1 = np.random.randint(1, 6, size=(3,2))
matrix_2 = np.random.randint(1, 6, size=(2,4))

print(f"{matrix_1}\n\n{matrix_2}\n")

print(f"matrix_1 * matrix_2 = \n{np.dot(matrix_1, matrix_2)}")

[[4 5]
 [4 1]
 [5 2]]
[[5 1 1 2]
 [1 4 5 1]]

matrix_1 * matrix_2 = 
[[25 24 29 13]
 [21  8  9  9]
 [27 13 15 12]]


7) Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [16]:
matrix = np.random.uniform(0, 1, size=(3,3))
print(matrix)
print("------------------------------------")
print(matrix.transpose())

[[0.87388549 0.12377514 0.87266821]
 [0.91433987 0.93092995 0.28301289]
 [0.77817681 0.13731061 0.9527964 ]]
------------------------------------
[[0.87388549 0.91433987 0.77817681]
 [0.12377514 0.93092995 0.13731061]
 [0.87266821 0.28301289 0.9527964 ]]


8) Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [17]:
matrix_1 = np.random.randint(1, 11, size=(3,3))
matrix_2 = np.random.randint(1, 11, size=(3,3))
matrix_1 - matrix_2

array([[ 5,  4, -5],
       [-3,  4,  3],
       [ 3,  2, -3]])

9) Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

In [23]:
matrix_1 = np.random.randint(-5, 5, size=(3,3))
matrix_2 = np.random.randint(-5, 5, size=(3,3))
print(matrix_1)
print("-----------------------")
print(matrix_2)
np.dot(matrix_1, matrix_2)

[[-2 -4  3]
 [-4 -3 -1]
 [-5  4  3]]
-----------------------
[[-3 -2 -5]
 [ 2 -2 -4]
 [ 0  4  0]]


array([[-2, 24, 26],
       [ 6, 10, 32],
       [23, 14,  9]])

10) Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [27]:
matrix = np.random.uniform(-1, 1, size=(3,3))
print(matrix)
print("---------------------------------------")
matrix.sum(axis=0).reshape(3, 1)

[[ 0.90957824 -0.26558847  0.20863109]
 [ 0.92744967 -0.24526578  0.8220908 ]
 [ 0.75129338  0.6772642   0.40535157]]
---------------------------------------


array([[2.58832129],
       [0.16640995],
       [1.43607346]])